### ISSUE TITLE
Version update automation uses wrong source

### ISSUE THREAD

**Issue by janjagusch** [conda-forge/quetz-client-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The version update automation uses the wrong source. In https://conda-forge.org/status/#version_updates you can see that it tried to release `quetz-client` 0.6.1, but that's the [quetz-server version](https://github.com/mamba-org/quetz/releases/tag/v0.6.1).

<img width="802" alt="image" src="https://user-images.githubusercontent.com/25852654/221826313-76c94d88-75f1-443c-a2d2-cabc7dc4a5f2.png">

I also think that this bug is related to https://github.com/conda-forge/quetz-feedstock/issues/29.

### Installed packages

```shell
not relevant
```

### Environment info

```shell
not relevant
```

**Comment by pavelzw** [comment]
Let's hope that [regro/cf-graph-countyfair#1](https://github.com/regro/cf-graph-countyfair/pull/1) fixes this 😅

**Comment by janjagusch** [comment]
@pavelzw, thanks for helping to resolve this! 🙏
